export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg-1.svg').default,
    alt: 'Man with a dollar sign',
    dark: true,
    primary: true,
    darkText: false,
}
export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a smartphone or a computer.',
    buttonLabel: 'Learn More',
    imgStart: false,
    img: require('../../images/svg-2.svg').default,
    alt: 'Man sitting with a laptop outside',
    dark: false,
    primary: false,
    darkText: true,
}
export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join out Team',
    headline: 'Creating an account is extremely easy',
    description: 'Get everything set up and ready in under 10 minutes. All you need to do is add your information and you\'re ready to go.',
    buttonLabel: 'Start Now',
    imgStart: true,
    img: require('../../images/svg-3.svg').default,
    alt: 'Man holding big bank card',
    dark: false,
    primary: false,
    darkText: false,
}